server:
  port: 8080
  address: 0.0.0.0   # ğŸ‘ˆ ì´ê²Œ ê¼­ í•„ìš”í•¨ (ì™¸ë¶€ ì ‘ì† ê°€ëŠ¥í•˜ë„ë¡ ì„¤ì •)


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shoppingmall?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: mypassword   # ë„¤ê°€ mysql_secure_installation ì—ì„œ ì„¤ì •í•œ root ë¹„ë²ˆ
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create   # ì‹¤í–‰í•  ë•Œë§ˆë‹¤ í…Œì´ë¸” ìƒˆë¡œ ìƒì„± (ì´ˆê¸° ê°œë°œ ë‹¨ê³„ì— ì í•©)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
  jwt:
    secret: your-secret-key-here
    expiration: 3600000